on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  update-translation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.12]
    steps:
      - uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - run: sudo apt-get install -y gettext
      - run: pip install requests cogapp polib transifex-python blurb wlc tqdm
      - uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - run: python -Werror -m cogapp -rP README.md
        env:
          KEY: ${{ secrets.KEY }}
      - run: git config --local user.email github-actions@github.com
      - run: git config --local user.name github-actions[bot]
      - run: python .update-translation.py pl
        env:
          KEY: ${{ secrets.KEY }}
      - uses: ad-m/github-push-action@master
        with:
          branch: ${{ matrix.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: translation-updated
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.12, 3.11]
    needs: ['update-translation']
    continue-on-error: true
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - run: pip install sphinx-lint
      - uses: actions/checkout@master
        with:
          ref: ${{ matrix.version }}
      - run: sphinx-lint
  build-translation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.12, 3.11, '3.10', 3.9, 3.8]
        format: [html, latex]
    needs: ['update-translation']
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - uses: actions/checkout@master
        with:
          repository: python/cpython
          ref: ${{ matrix.version }}
      - run: make venv
        working-directory: ./Doc
      - uses: actions/checkout@master
        with:
          ref: ${{ matrix.version }}
          path: Doc/locales/pl/LC_MESSAGES
      - run: git pull
        working-directory: ./Doc/locales/pl/LC_MESSAGES
      - run: make -e SPHINXOPTS="-D language='pl' -D gettext_compact=0 -W --keep-going" ${{ matrix.format }}
        working-directory: ./Doc
      - uses: actions/upload-artifact@master
        with:
          name: build-${{ matrix.version }}-${{ matrix.format }}
          path: Doc/build/${{ matrix.format }}
  output-pdf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.12, 3.11, '3.10', 3.9, 3.8]
    needs: ['build-translation']
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-${{ matrix.version }}-latex
      - run: sudo apt-get update
      - run: sudo apt-get install -y latexmk texlive-xetex fonts-freefont-otf xindy
      - run: make
      - uses: actions/upload-artifact@master
        with:
          name: build-${{ matrix.version }}-pdf
          path: .
